### ISSUE TITLE
Connector error while connecting

### ISSUE THREAD

**Issue by Semavo** [Gladior-B-V/data-hub-app#10]
Hey,
I can't link my Google Business Profile due to this error. A few days ago everything was still working.

Do you know what it is? I've tried reconnecting everything a few times, deleting the cache, re-granting access and nothing works.
![Screenshot_325](https://user-images.githubusercontent.com/123973511/215528819-49707642-55f7-4098-84e8-cf366f596404.png)

**Comment by daannijkamp** [comment]
Hi @Semavo,

Thanks for reporting. I'd like to take a look.
Can you send me your user ID? datahubapp.gladior.com -> Edit Profile -> gray ID at the bottom of the page

![Screenshot from 2023-01-30 17-13-31](https://user-images.githubusercontent.com/1774060/215531603-8bbf5130-b02c-457f-b4eb-4abcfe7c2af1.png)

**Comment by Semavo** [comment]
Sure, my ID: google_117376812761000666758

**Comment by Semavo** [comment]
@daannijkamp 
Hi, do you already know something? :)

**Comment by daannijkamp** [comment]
@Semavo Can you try again? I really hope I was able to fix this bug,

**Comment by zoedufrenne** [comment]
@Semavo We've made an adjustment to the Data Hub. This adjustment should resolve your issue, could you try again?

**Comment by Semavo** [comment]
@zoedufrenne 
Hello, thank you! The connection is already working. However, the problem appears in displaying data in Looker. In many places I get the message "Looker Studio cannot connect to the dataset". I use a copy of the report that works in other accounts. As a connector, I only use Google Business Profile, without any others that could potentially break something.

**Comment by Semavo** [comment]
I will add that once in a while in Looker the necessary data is displayed, but later when I refresh it disappears again. Could it be that you have an overload on your side?

**Comment by daannijkamp** [comment]
Hi @Semavo,

Google is having issues with the Google Business Profile API. I get the message "The service is currently unavailable." when I want to retrieve data. Unfortunately there is little we can do about this.

**Comment by Semavo** [comment]
Hey @daannijkamp @zoedufrenne ,

Could you please check why none of the company profiles I want to import from the second credential are loading? Only the first connection works.

Admittedly, I don't get the error "There was an error communicating with the data provider" like at the beginning, but I can't use any of the connections created in Looker later. In the Data Hub panel, connections from all other credentials look different than others - the name of the GBP profile and its link are not loaded.

**Comment by Semavo** [comment]
@zoedufrenne @daannijkamp ???

**Comment by zoedufrenne** [comment]
Hi @Semavo we are working on a fix. I keep you posted, when the fix is live.

**Comment by Semavo** [comment]
@zoedufrenne 
Hi!
Ok thx, so I'm waiting for news :)

**Comment by zoedufrenne** [comment]
Hi @Semavo the Google Business Profile connector is working again. You should refresh the data fields and then you'll see some new and deleted fields. This is because of the new API. Can you let me know if it's working?

**Comment by Semavo** [comment]
Thank you! ❤❤❤❤❤
