### ISSUE TITLE
No Options were provided for "group"

### ISSUE THREAD

**Issue by amanda-jacquart** [Gladior-B-V/data-hub-app#11]
Hello, I saw this same issue in another post but not sure how it was resolved, and didn't want to bring up the issue in the same post when it looks like there are other things happening there as well. I connected a different email account that has the connects since the original email was removed from the connects. I have owner rights to all the GMB accounts but nothing is showing up. 

![image](https://user-images.githubusercontent.com/88114105/216464663-1bfcc77e-b0d8-4d45-9e8e-d2bb75922af3.png)

**Comment by zoedufrenne** [comment]
Hi @amanda-jacquart 
There is a new API for GBP. We are currently busy with connecting the connector to this new API.
I'll inform you when this version is live.

**Comment by zoedufrenne** [comment]
Hi @amanda-jacquart 
The new version is live, can you let us know if you can now connect to the Google Business profile connector?

**Comment by amanda-jacquart** [comment]
Hello @zoedufrenne I was able to get the account connected thank you for working on that!  

Now I am running into a different error. I currently have follower's on Looker Studio but it is giving an unknown error with error id: 4b0eddc3. I have disconnected and reconnected the data and tried to update the data point, even adding a new data point and keep getting this error. Maybe it is just a time thing since Looker was also having issues yesterday with all it's connectors. 


![image](https://user-images.githubusercontent.com/88114105/227253303-0a79524f-df30-4aa0-a66e-3f5a3f40278c.png)

**Comment by zoedufrenne** [comment]
Hi @amanda-jacquart ,  could you maybe share the dashboard with data-dashboards@gladior.com? 
I'll check the issue with development!

**Comment by amanda-jacquart** [comment]
@zoedufrenne I shared the GMB dashboard I have let me know if the access needs to be changed though

**Comment by zoedufrenne** [comment]
Hi @amanda-jacquart  thanks for sharing. I see what the issue is, there was an update from GMB for the connector. Some data fields aren't available anymore. Such as: 
- Queries direct
- Queries indirect

The information about phone calls will also change in about a month. 
Request for driving directions is still possible to create, because I only have view rights, I can't see which metrics are connected to the chart. The metric followers is indeed not working.

I'll let development check this metric and see if we can fix it! I'll keep you updated!

**Comment by amanda-jacquart** [comment]
@zoedufrenne Good morning, thank you so much for this information it really helps me a lot! Are they going to be removing the phone calls completely or changing what they track for phone calls?  

I did update the access to the dashboard to editor, just incase you need to take a closer look. 

I appreciate your help so much and keeping me updated on this!

**Comment by zoedufrenne** [comment]
@amanda-jacquart Here you can see which fields are going to be changed: https://developers.google.com/my-business/content/sunset-dates
