### ISSUE TITLE
Google Business Group Data

### ISSUE THREAD

**Issue by zLinister** [Gladior-B-V/data-hub-app#12]
Hi,

I have two questions:
1) Is there a way to pull data for an entire locations group from google my business to report on it on Data studio? for example currently i can only have the data for one location at a time but majority of clients i work with have more than one location that they like to see an overview of the performance for, so how to achieve that?

2) When will this tool become paid? and how much will it be? I need to know this information before I move the clients I have to this api.

Thanks,
Lin

**Comment by zoedufrenne** [comment]
Hi @zLinister ,

Thanks for your message!

There is a way to pull multiple locations with the Google Business Profile Connector. We have a paid subscription for €95 per month, where you'll get extras in the Data Hub and the Google Business Profile + Connector. With the plus version you can connect all the locations in one dashboard. To keep the dashboard a little up to speed, you'll need to use the cache option (included in the paid subscription). 

If you would like, we can create a template just for you. With your own template, you can directly connect your clients to your dashboard. For creating a template, we ask a developer fee. This depends on what you want to see in the dashboard. To discuss this we could plan a teams-meeting to discuss the possibilities. We can show you then directly how the Google Business Profile + connector works. 

The version that you are using at the moment stays for free! We only develop extras like caching, multiple data sources templates & GBP+ Connector for a paid subscription. 

Zoé du Frenne
