### ISSUE TITLE
Unknown Error - There was an error communicating with the service.

### ISSUE THREAD

**Issue by klcem** [Gladior-B-V/data-hub-app#13]
I am unable to connect to GBP/GMB from lookerstudio or the datahub 

[
![Screen Shot 2023-03-23 at 2 56 38 PM](https://user-images.githubusercontent.com/128624036/227320168-51d00cdb-7f4f-45a6-95d4-77ec9b4a4407.png)
![Screen Shot 2023-03-23 at 2 56 33 PM](https://user-images.githubusercontent.com/128624036/227320170-855c1a89-1f9f-47d1-83c9-e7cd4b25d97c.png)
](url)

**Comment by zoedufrenne** [comment]
Replied at the other issue --> https://github.com/Gladior-B-V/data-hub-app/issues/8
