### ISSUE TITLE
Can not connect data source to datahubapp.gladior  an error has occurred

### ISSUE THREAD

**Issue by socialelitepl** [Gladior-B-V/data-hub-app#14]
When i add my Facebook account credentials, nothing is happened next. When I return to the datahubapp page it spins a circle. The problem lasts for a month. The same situation occurs when I try to connect my Pinterest account. 

<img width="900" alt="Zrzut ekranu 2023-03-29 o 14 46 47" src="https://user-images.githubusercontent.com/129292720/228539646-e964f172-1276-4f6f-b542-6256f5bba1a9.png">

**Comment by zoedufrenne** [comment]
Hi @socialelitepl thanks for letting us know! I let development know and keep you updated about the fix.

**Comment by zoedufrenne** [comment]
Hi @socialelitepl, we've mad an update! can you let us know if it fixed your issue?
