### ISSUE TITLE
Facebook Insights Limit

### ISSUE THREAD

**Issue by hiddenkust** [Gladior-B-V/data-hub-app#15]
Hello! I'm having the following problem with data from Facebook: 

Time range too long: There cannot be more than 93 days (8035200 s) between since and from.

Is it really a limitation from Facebook's part, or something that can be fixed? Cause I can see all of the historical data through native Insights.

**Comment by zoedufrenne** [comment]
HI @hiddenkust , Facebook Insights gives a lot of limitations to the data in their API. Can you let us know by which metrics you'll get these errors?

**Comment by hiddenkust** [comment]
I was using the follower count, likes and unlikes, but after reviewing the data on Facebook, seems like they stopped providing this statistic for stretches of time longer than 90 days. So I guess we are limited to that in any case, sorry for the inconvenience. you can consider the issue solved :).
