### ISSUE TITLE
Can't connects to GMB

### ISSUE THREAD

**Issue by TiagoGra** [Gladior-B-V/data-hub-app#16]
Hi there,

I´m trying to connect to GMB but for some reason is not possible.
![image](https://user-images.githubusercontent.com/132343728/235622387-368544bb-60f6-43b0-857d-7f6486bebea9.png)

I´m already using Facebook and Linkedin but for GMB give that error.

Can you help?

Thanks

**Comment by zoedufrenne** [comment]
Hi @TiagoGra,

Thanks for letting us know. Can you try to revoke acces and then try again to make the connection?
