### ISSUE TITLE
Cannot connect a second facebook page

### ISSUE THREAD

**Issue by bmhazeleger** [Gladior-B-V/data-hub-app#17]
I connected 1 FB page to the Facebook Insights, but when i want to create a new data source i can just select the already connected facebook page. How can i connect a second page?

**Comment by zoedufrenne** [comment]
Hi @bmhazeleger, You can use the Data Hub connector to connect multiple pages of facebook. You just need to make more data sources in your workspace [@ https](https://datahubapp.gladior.com/) Can you let us know if it worked?
