### ISSUE TITLE
Not able to pull in purchases or purchase conversion value from Facebook Ads

### ISSUE THREAD

**Issue by jeremydixon** [Gladior-B-V/data-hub-app#18]
Aș per title Im not able to pull in purchases or purchase conversion value from Facebook Ads I have tried the following dimensions

Action Value Purchases
Website Purchases
Purchases

I have sales data in FB but it isn’t pulling into the data

**Comment by zoedufrenne** [comment]
Hi @jeremydixon , 
This is probably because it's a custom pixel event. We don't support those in our connector. See also our FAQ. https://datahub.gladior.com/data-sources/support-facebook-ads-connector/
