### ISSUE TITLE
Can't connect my pages from my business

### ISSUE THREAD

**Issue by GeorginaAlcaraz** [Gladior-B-V/data-hub-app#19]
My report had some facebook pages already connected and now throws this error:
Unknown Error - There was an error communicating with the service.
ID de error: 898602b7

When I try to reconnect the pages, it only gives me te option of the pages that are not on my business. But the one I'm trying to connect is on y business.

<img width="440" alt="Captura de pantalla 2023-07-05 a la(s) 10 09 14" src="https://github.com/Gladior-B-V/data-hub-app/assets/123579191/46e269ce-de32-4c02-bef9-2df9eade4a7a">
<img width="957" alt="Captura de pantalla 2023-07-05 a la(s) 10 04 49" src="https://github.com/Gladior-B-V/data-hub-app/assets/123579191/321e0fc2-7fc6-4c85-858e-eb996b67959f">

**Comment by zoedufrenne** [comment]
Hi @GeorginaAlcaraz thanks for passing it on. We are getting multiple reports about this problem. Could I have your Data Hub ID? (You can find this under, edit profile, in the upper right corner of the data hub) Then I will look at the issue with Development and we will see if it can be resolved.

**Comment by GeorginaAlcaraz** [comment]
Hi, sure: google_100873252497336233150
<img width="425" alt="Captura de pantalla 2023-07-07 a la(s) 10 42 02" src="https://github.com/Gladior-B-V/data-hub-app/assets/123579191/da6aaae9-cf71-4161-b585-d7938f6c5e94">

**Comment by chrisgdclarke** [comment]
Having exactly the same issue. Facebook page not appearing, only those outside of a business account are showing on the dropdown.

**Comment by zoedufrenne** [comment]
Hi this issue is being discussed in the following thread: https://github.com/Gladior-B-V/facebook-insights-connector/issues/11 
I'll  close this issue and keep you updated in the other one.
