### ISSUE TITLE
Error Validating Access Token: Expired Session

### ISSUE THREAD

**Issue by gbwick** [Gladior-B-V/data-hub-app#2]
I've been using the FB ads to Data Studio connector however have recently ran into an issue where FB data will not push. Any thoughts on what could cause this? I've read through the support page but can't find anything touching on it. I've removed access and reconnected a couple times with no success. Here is an screenshot of the issue I am having: https://imgur.com/a/TOJihYK

**Comment by zoedufrenne** [comment]
Hi @gbwick ,

Go to https://datahubapp.gladior.com/  and follow these steps:

1. login
2. Click on ‘+ Create’ and select the data provider (Facebook ads)
3. Add your credential again. Your credential is already there, but you need to add it again to make a new connection.

When you’ve connected your credential again, your session is renewed. The data source in your Data studio dashboard will work automatically again. 

See faq: https://datahub.gladior.com/data-sources/support-facebook-ads-connector/
