### ISSUE TITLE
 Search keyword on GMB error

### ISSUE THREAD

**Issue by jaderssouza** [Gladior-B-V/data-hub-app#21]
Hello, the search keyword on GMB show up "null" error. See the attachment please. Can you help me?
![search keyword GMB error](https://github.com/Gladior-B-V/data-hub-app/assets/118145178/c401580e-9238-48cf-a2e5-0b68fdfa1d30)

**Comment by zoedufrenne** [comment]
@jaderssouza thanks for letting us know. However, Search Keyword cannot be combined with total impressions. Total impressions is a metric that indicates how many times the GBP location was shown. Search Keyword only indicates which terms were searched for. This is a stand-alone field that cannot be combined. This is also not combinable with date.

**Comment by jaderssouza** [comment]
Thank you for your support. I add Search Keyword as dimension and insight value as metric. It worked!!!
