### ISSUE TITLE
Can't connect to Facebook location pages

### ISSUE THREAD

**Issue by ESGITR** [Gladior-B-V/data-hub-app#22]
Good morning,

I'm unable to connect to my Facebook location pages with the insights plugin in Looker studio. The links in datahub are broken and credentials are removed.

When I try to renew the credentials I only get acces to the main page of my company.

Kind Regards,
Lloyd

**Comment by zoedufrenne** [comment]
HI @ESGITR,

We've made an update in our Facebook Insights connector. You need to go to your Facebook account and click in the right corner on your profile and go to settings & privacy > settings. Then go to business integrations in the left menu and revoke acces of the Gladior Insights Connector. 

When you've done this, go to the data hub (https://datahubapp.gladior.com/workspace) and create data source > Facebook Insights and connect again your credentials (even it's already there!). 

Then you'll get a pop-up with a few checkboxes that you need to check and make the connection to the data hub.

If you followed these steps you'll be able to connect to all the accounts you have acces to. 

Please let me know if it worked!

**Comment by ESGITR** [comment]
Hi Zoe,

I’ve done the steps you’ve provided but without success... I can’t reconnect my excising sources nor create select a page to create a new one.

Kind Regards,
Lloyd

Van: zoegerritsen ***@***.***>
Verzonden: maandag 24 juli 2023 14:46
Aan: Gladior-B-V/data-hub-app ***@***.***>
CC: Marketing Euro Shop ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Gladior-B-V/data-hub-app] Can't connect to Facebook location pages (Issue #22)


HI @ESGITR<https://github.com/ESGITR>,

We've made an update in our Facebook Insights connector. You need to go to your Facebook account and click in the right corner on your profile and go to settings & privacy > settings. Then go to business integrations in the left menu and revoke acces of the Gladior Insights Connector.

When you've done this, go to the data hub (https://datahubapp.gladior.com/workspace) and create data source > Facebook Insights and connect again your credentials (even it's already there!).

Then you'll get a pop-up with a few checkboxes that you need to check and make the connection to the data hub.

If you followed these steps you'll be able to connect to all the accounts you have acces to.

Please let me know if it worked!

**Comment by zoedufrenne** [comment]
HI @ESGITR, Can you make the connection again with Facebook Insights! We resolved the connection approx. 3 weeks ago. See also issue: https://github.com/Gladior-B-V/facebook-insights-connector/issues/11
