### ISSUE TITLE
Community plugin error Lookerstudio

### ISSUE THREAD

**Issue by Poetszorg** [Gladior-B-V/data-hub-app#23]
![image](https://github.com/Gladior-B-V/data-hub-app/assets/122869929/7f6eade9-955c-41af-aaa7-1bbd24b026e6)

I get the error above in all my dashboards using the data hub community plugin.

**Comment by zoedufrenne** [comment]
Hi @Poetszorg ,

Bedankt voor je bericht. 
Kan je misschien aangeven welke bron je probeert te koppelen en wanneer je deze melding precies krijgt? Zelf zien wij in de back end geen foutmeldingen binnen komen voor de algemene data hub connector.

Ik hoor graag van je!

**Comment by Poetszorg** [comment]
Beste @zoedufrenne,

Bedankt voor je reactie. Alles werkt inmiddels weer. Dit probleem hebben wij maanden geleden eerder gehad vandaar dat ik 'm even meld. De foutmelding kwam niet na een nieuwe koppeling maar alle diagrammen die via de connector zijn gekoppeld kregen een foutmelding en de data was niet langer zichtbaar. Als ik op de error klik kreeg ik deze melding.

Mvg,

Merijn
