### ISSUE TITLE
AFAS link to Looker

### ISSUE THREAD

**Issue by Hamed208** [Gladior-B-V/data-hub-app#25]
AFAS:  try to coonet to Looker   but  I can see data in Algemeen (Just profit) but not data in CRM (Forecast)

**Comment by zoedufrenne** [comment]
Hi @Hamed208, Where do you want to show the data? Do you see the data coming in in connect.afas? Please a little more information so I can help you. With our connections, we are still getting data in the dashboards.

**Comment by Hamed208** [comment]
Hi,  Actually I can see some data that is link from AFAS to Looker    but I can not see a specific data that I need in "Getconectoren" in AFAS . I suppose I have to bring from Updateconnectoren but I have no idea how to do that,

Thank you indvance for your kind help

Hamed

**Comment by zoedufrenne** [comment]
Hi @Hamed208

You need to create your own getConnectors in AFAS. This will allow you to connect all the data you want to see in your Looker Studio dashboard. Should you need help with this, we can help. This is a paid service though.

**Comment by Hamed208** [comment]
Thanks for your comment.  Yes I need help and I am wondering how much is cost?  With the best regards Haned


Verzonden via Yahoo Mail voor iPhone


Op vrijdag, september 8, 2023, 4:18 PM schreef zoegerritsen ***@***.***>:




Hi @Hamed208

You need to create your own getConnectors in AFAS. This will allow you to connect all the data you want to see in your Looker Studio dashboard. Should you need help with this, we can help. This is a paid service though.

**Comment by Hamed208** [comment]
Hi I couldnot find paid service in your website   would you end me the link

Regards
Hamed

**Comment by zoedufrenne** [comment]
Hi @Hamed208, is it possible to set up a meeting? We could set up a Service Level Agreement, but it depends on the amount of work. In the meeting we can discuss the wishes for the getConnectors. Our hourly rate is €115,-. We are a digital agency in the Netherlands, working a lot with AFAS. This is our website: https://www.gladior.com/.

**Comment by Hamed208** [comment]
Hi
Many thanks for your kind support.  I already find the problem (filter autorisation)  . I would touch with you if there is more help.  
With the Best RegardsHamed

    On Tuesday, September 12, 2023 at 09:20:58 AM GMT+2, zoegerritsen ***@***.***> wrote:  
 
 


Hi @Hamed208, is it possible to set up a meeting? We could set up a Service Level Agreement, but it depends on the amount of work. In the meeting we can discuss the wishes for the getConnectors. Our hourly rate is €115,-. We are a digital agency in the Netherlands, working a lot with AFAS. This is our website: https://www.gladior.com/.
