### ISSUE TITLE
Currency EUR mandatory on Facebook Ads Connector

### ISSUE THREAD

**Issue by Madda17** [Gladior-B-V/data-hub-app#26]
Hi! I could see that with the last adjustments on the Facebook Ads connector, the only available currency is the EUR for price metrics. Is there any way to change this? Thanks!

**Comment by zoedufrenne** [comment]
Hi @Madda17 in the facebook ads connector there is a field called account currency, this shows the currency of your account. See for all available fields here: https://datahub.gladior.com/data-sources/support-facebook-ads-connector/

**Comment by Madda17** [comment]
Hi Zoe! The problem is that my account does not use EUR. The list you pasted shows the EUR as default currency on the cost metrics, we should be able to mantain our currency account in these metrics too. How can it be solved?

![WhatsApp Image 2023-09-27 at 09 24 21](https://github.com/Gladior-B-V/data-hub-app/assets/129771123/068f84f1-b358-4255-a2ba-ecb67685a1f1)
![WhatsApp Image 2023-09-27 at 09 24 35](https://github.com/Gladior-B-V/data-hub-app/assets/129771123/87f14e1d-81cf-4999-98ae-da040d96e81f)

**Comment by zoedufrenne** [comment]
Hi @Madda17 , the metrics that are set in currency_eur can't be changed. It is a lot harder to get this metrics when we select the account set currency. It will took a lot of more development hours, and because it's a free connector, we set this to euro because most of our clients use it. In Looker Studio you can manually change it to the currency you want to see.

**Comment by Madda17** [comment]
Thank you for the explanation! I understand the reason of this choice of course. Can you give me some information about how to change the currency directly on Data Studio? I tried but I couldn't find it. See you!

**Comment by zoedufrenne** [comment]
Hi @Madda17 you can click on SUM of AVG etc. and then change the data type. If you make the adjustment in the added source it will automatically change to the metric you want.
