### ISSUE TITLE
Community connector error

### ISSUE THREAD

**Issue by brunoccan** [Gladior-B-V/data-hub-app#27]
Hello. The connector has stopped providing Facebook Ads data in Looker Studio, where the following message appears:

Community connector error
An error occurred caused by the community connector. If the problem persists, report it to the connector vendor.

Connector Details
Unknown Error - There was an error communicating with the service.

**Comment by zoedufrenne** [comment]
Hi @brunoccan, Could revoke acces to the connector in Looker Studio and create a new credential in the Data hub app?  please let me know if this worked. I checked our connections but these still work
