### ISSUE TITLE
Looker Studio connecting with Pinterest

### ISSUE THREAD

**Issue by ajb181** [Gladior-B-V/data-hub-app#28]
When using the connector with Pinterest we are able to get a lot of data however when we try and use the attributes of pin image, pin description, pin url and a few others it crashes the connector and we get this issue.  removing these data sources solves the issue and the remaining data is shown?

<img width="622" alt="Screenshot 2023-11-07 at 10 58 49 AM" src="https://github.com/Gladior-B-V/data-hub-app/assets/150086301/1bfb956f-439e-4343-b4b5-af58c3565889">
<img width="1334" alt="Screenshot 2023-11-07 at 10 58 36 AM" src="https://github.com/Gladior-B-V/data-hub-app/assets/150086301/c70e51c5-f9b2-4517-863e-f687056a7260">
<img width="1491" alt="Screenshot 2023-11-07 at 10 58 07 AM" src="https://github.com/Gladior-B-V/data-hub-app/assets/150086301/2303dbee-2533-4e01-a08e-9f52b9c77eb8">

**Comment by zoedufrenne** [comment]
Hi @ajb181, we've made an update in the connector. Can you check if it's a solution for you? :)
