### ISSUE TITLE
Instagram Insights Connector error

### ISSUE THREAD

**Issue by m-karakus** [Gladior-B-V/data-hub-app#29]
I am getting this error message, can you provide a solution for this, please?

```
There was an error caused by the community connector. Please report the issue to the provider of this community connector if this issue persists.

Connector details
Unknown Error - There was an error communicating with the service.

Error ID: 2434f695  
```

![image](https://i.imgur.com/5f8q0oH.png)

**Comment by zoedufrenne** [comment]
Hi @m-karakus Could you revoke acces of the connector in Looker Studio and then make a new connection in de Data hub app? 
please let me know if this worked. There was an update from Facebook with the Instagram API that's why you got error messages.
