### ISSUE TITLE
Error of my access token

### ISSUE THREAD

**Issue by SamuelHenrique212535** [Gladior-B-V/data-hub-app#3]

**Comment by zoedufrenne** [comment]
Go to https://datahubapp.gladior.com/  and follow these steps:

1. Login
2. Click on ‘+ Create’ and select the data provider.
3. Add your credential again.

Your credential is already there, but you need to add it again to make a new connection.

When you’ve connected your credential again, your session is renewed. The data source in your Data studio dashboard will work automatically again.
