### ISSUE TITLE
Indeed connector currency

### ISSUE THREAD

**Issue by chaclarkeyoke** [Gladior-B-V/data-hub-app#30]
Hi, 

The indeed connector works great, but always converts the currency to EUR by default, when many of the data sources we're connecting to are in GBP, as well as EUR or USD. 

Is there any fix for this, other than manually changing each element in the report? I cannot edit the currency dimension in the data source.

Thanks

<img width="604" alt="Screenshot 2023-12-14 at 11 46 04" src="https://github.com/Gladior-B-V/data-hub-app/assets/153825272/38c5dcf1-e1ab-4c7f-b7fc-926bb7da66cd">

**Comment by zoedufrenne** [comment]
Hi @chaclarkeyoke ,

We had to set a default and we are located in the Netherlands. That's why it's set to euro. You can change the currency in your report to the currency of your desire. 

We won't change the default in the connector.
