### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by Easyschools** [Gladior-B-V/data-hub-app#31]
There was an error caused by the community connector. Please report the issue to the provider of this community connector if this issue persists.

Connector details
(#3018) The start date of the time range cannot be beyond 37 months from the current date

Error ID: 05b5fd70

**Comment by zoedufrenne** [comment]
@Easyschools the error you get has to do with the date selector, as the message shows:

"The start date of the time range cannot be beyond 37 months from the current date"

You can't show data beyond 37 months, further back is not possible with the API.
