### ISSUE TITLE
Connection Error with Google My Business

### ISSUE THREAD

**Issue by ctopping1** [Gladior-B-V/data-hub-app#32]
We get this error no matter what. We have tried revoking access, and trying, but nothing works. This is only for google my business connection. Thank you

![data-boo-connection](https://github.com/Gladior-B-V/data-hub-app/assets/156518951/68e91e92-7cb4-4960-a206-bbdec6940056)
![data-boo-connection-2](https://github.com/Gladior-B-V/data-hub-app/assets/156518951/281dea16-ed5d-4369-a088-11a64b7b7a49)

**Comment by zoedufrenne** [comment]
Hi @ctopping1 , thanks for sharing your screenshots. The connector is working on our side and don't get any errors. Are there groups connected to the e-mail you try to connect to the GBP connector?
