### ISSUE TITLE
Microsoft Ads Not Working

### ISSUE THREAD

**Issue by aykacmusa** [Gladior-B-V/data-hub-app#33]
The Microsoft ads connector does not work it says no accounts found

**Comment by aykacmusa** [comment]
![image](https://github.com/Gladior-B-V/data-hub-app/assets/124694172/2ea0b599-9730-430b-99fa-938a0ef155d5)

**Comment by aykacmusa** [comment]
Iv tried 4 different accounts all like this

**Comment by aykacmusa** [comment]
I am super admin on them all

**Comment by zoedufrenne** [comment]
Hi @aykacmusa we don't see any errors in the connector. We can also connect with the connector. Do you also have rights to connect with a 3rd party connector?

**Comment by aykacmusa** [comment]
What do you mean rights? i approved it in Microsoft ads when it popped up

**Comment by zoedufrenne** [comment]
@aykacmusa i'm trying to find a reason why you can't see the accounts. Beacause the connector is working correctly. Can you share your Data hub ID? (the code when you click on your account, in the right corner).

**Comment by aykacmusa** [comment]
Public avatar
Upload new avatar
Profile
Name
Update profile

Do you want to delete this account, contact support
<https://datahub.gladior.com/support>
google_111449803070422509257

**Comment by aykacmusa** [comment]
Is that what you needed?

**Comment by aykacmusa** [comment]
hello any update?

**Comment by zoedufrenne** [comment]
@aykacmusa our developers are still checking what the reason is why it isn't working on your side. I keep you informed when I have an update.

**Comment by rkooiker** [comment]
@aykacmusa When retreiving the accounts we recieve the following error message:
```
{
  error: 'invalid_grant',
  error_description: 'AADSTS70000: 

> Account security interrupt for collecting proof, when user account is found as compromised

 Trace ID: 182848af-8cd9-4878-b8e0-d9397e18a400 Correlation ID: 5a1f0537-58bf-4871-939b-5f5d3e659858 Timestamp: 2024-02-21 13:44:54Z',
  error_codes: [ 70000 ],
  timestamp: '2024-02-21 13:44:54Z',
  trace_id: '182848af-8cd9-4878-b8e0-d9397e18a400',
  correlation_id: '5a1f0537-58bf-4871-939b-5f5d3e659858',
  error_uri: 'https://login.microsoftonline.com/error?code=70000'
}
```

This is outside of our control. I recommend that you reach out to microsoft support. Once the issue is resolved you can try to connect again.
