### ISSUE TITLE
Community connect error

### ISSUE THREAD

**Issue by yichusheng** [Gladior-B-V/data-hub-app#35]
Hi,

I have been using indeed conncetor for several months and it worked well. But recently I have community error like this:
<img width="666" alt="Screenshot 2024-03-26 at 7 51 57 PM" src="https://github.com/Gladior-B-V/data-hub-app/assets/90480382/01d30693-7a53-4f91-9947-04ee3e6ec95c">
Can you help me with this issue? Thank you!

**Comment by yichusheng** [comment]
This problem has been going on for a couple weeks now. I can see the indicators, but there is no data to show. And my gray ID is: google_100590437386129402716

<img width="160" alt="Screenshot 2024-03-26 at 8 16 06 PM" src="https://github.com/Gladior-B-V/data-hub-app/assets/90480382/91a6ae94-89d8-463c-a90c-4ac339c80821">

**Comment by zoedufrenne** [comment]
Hi @yichusheng, Can you try to connect your credential again to the datahubapp.gladior.com (even if it's already there). Just add your credentials as a new credential. Indeed works with 2fa and sometimes you have to make a new connection with the connector to verify that you still are account owner. Can you let me know if it works? :)

**Comment by yichusheng** [comment]
Hi @zoedufrenne, I have revoked the credential and added it agian but it does not work. I got the same error report in looker studio.

**Comment by zoedufrenne** [comment]
Hi @yichusheng you don't need to revoke the credential. Just add a new one then your first credential will automatically update to the new login. I've send your data hub id to development and I will keep you updated what the results are.

**Comment by jerry-from-mesmero** [comment]
I'm getting the same error as well, started at the end of March as well.  I've reconnected my credentials and continue to get the same errors.  I need to fix this or I must switch to another vendor. Help!
