### ISSUE TITLE
Facebook Insights: Pages aren't appearing under connector

### ISSUE THREAD

**Issue by ALL1E-MAE** [Gladior-B-V/data-hub-app#36]
My company has multiple Facebook pages connected to one account (the credential) of all the clients we manage. However, some clients pages aren't appearing on the Facebook Insights connector, and we're not sure why. We have full access to the page on Facebook.

We have tried revoking access, re-connecting, resetting DataHub, etc. multiple times. Is there something in the settings on the Facebook page that needs to be enabled for them to appear in the drop-down menu for the connector? We don't know why it's not appearing. 

Thank you in advance for any support you can provide! 

DataHub ID: google_109993665996910690326

**Comment by zoedufrenne** [comment]
Hi @ALL1E-MAE , when you make a connection with your facebook account. Do you see the other accounts there as well? As this screenshot: 
![image](https://github.com/Gladior-B-V/data-hub-app/assets/84766152/c5cbad4b-cb66-4c3b-96b8-202064d9c49e)
Are all the checkboxxes checked? 

If the accounts aren't shown here, it is about the correct rights to connect an external connector to these accounts.
