### ISSUE TITLE
Another Community Connector Error

### ISSUE THREAD

**Issue by jerry-from-mesmero** [Gladior-B-V/data-hub-app#37]
Since the end of March, I have lost connected to Facebook data through Data Hub on Looker Studio.   I've reset/reconnedted credentials, but still getting the same error.

This is a big problem and need to get it resolve or find another data vendor. Please help!

![Screenshot 2024-05-15 at 3 02 43 PM](https://github.com/Gladior-B-V/data-hub-app/assets/169951059/25be088a-2c65-44f4-8ec8-cca871b491f3)

**Comment by rkooiker** [comment]
Hi @jerry-from-mesmero, can you sure your Data Hub user id? This is the greyed out number found under your profile.

**Comment by jerry-from-mesmero** [comment]
yes, here it is 
google_114400395986881689618

The connector is working again now.  Not sure how it got fixed...?

**Comment by rkooiker** [comment]
Ah, glad to hear it got fixed.
