### ISSUE TITLE
Google Search Console: Incomplete data

### ISSUE THREAD

**Issue by mmotsakou** [Gladior-B-V/data-hub-app#38]
I connected our Search console account with Looker studio to monitor blog performance and it seems like it only shows ONE RESULT in queries while in Search console panel when i repeate the same search, I get more Queries.  I repeated this type of search for several blog pages and seems it always shows only one Query in looker studio. 

**Screenshots below:** 
![image](https://github.com/Gladior-B-V/data-hub-app/assets/58588579/d9479724-cbf2-4266-99f6-edb5f6d5d330)
![image](https://github.com/Gladior-B-V/data-hub-app/assets/58588579/8987c699-6af5-4160-a030-e5513306a053)

**Comment by rkooiker** [comment]
Hi @mmotsakou, this does not seem to impact any other dashboards, could you share your dashboard with service@gladior.com so that we can look further into the issue ?
