### ISSUE TITLE
Problemi interfaccia tra connettore Google Business Profile e Looker Studio

### ISSUE THREAD

**Issue by in3pida** [Gladior-B-V/data-hub-app#39]
Ciao, sto riscontrando problemi con il connettore Google Business Profile. Non riesco a trovarlo nella lista di connettori disponibili per Looker Studio perché restituisce un avviso con scritto "l'amministratore ha limitato l'accesso a questo connettore".

Allego screen.

Che significa? In che modo possiamo fare per avere accesso al connettore da Looker Studio?

Grazie mille. 

![image](https://github.com/Gladior-B-V/data-hub-app/assets/125992718/6b2b0366-9ac6-4e09-84c5-09d1e073fe05)

![Screenshot 2024-06-19 151804](https://github.com/Gladior-B-V/data-hub-app/assets/125992718/2a60b5f4-e9e6-48cf-a945-163c86a55869)

**Comment by rkooiker** [comment]
buongiorno, ciao tutti. 

This seems to be an issue with Looker. According to this thread: https://www.googlecloudcommunity.com/gc/Looker-Studio/Your-Admin-has-restricted-access-to-these-connectors/m-p/769346 the issue should be resolved now. Could you please verify?
