### ISSUE TITLE
Page Speed Insights breaking on Looker Studio

### ISSUE THREAD

**Issue by mae12012022** [Gladior-B-V/data-hub-app#4]
I would like to report an error. I've successfully connected the Page Speed Insights Connector to Looker Studio but it's not pulling any data. Here is the error.
![image](https://user-images.githubusercontent.com/119599768/205058341-3c5f8582-0dcb-4e8a-ada2-349034365dbc.png)

**Comment by zoedufrenne** [comment]
Hi @mae12012022,  

What kind of website did you fill in to the connector?
Could you maybe share your dashboard with data-dashboards@gladior.com? I will check with development the error!

Zoé du Frenne

**Comment by mae12012022** [comment]
Hello Zoe, thank you for your reply.

It's a content site. https://www.elliott.org
I have given access to ***@***.***
https://datastudio.google.com/reporting/b210a7ca-f31c-4c6c-87b0-dcfd19024130

Mae

**Comment by zoedufrenne** [comment]
Hi Mae,

Thanks for sharing.
We've fixed the issue and the connector is working again.

Good luck with building your dashboard.
Zoé du Frenne
