### ISSUE TITLE
Channable - Not possible to add Project ID

### ISSUE THREAD

**Issue by QplAyStylzQ** [Gladior-B-V/data-hub-app#40]
Hi!

I'm trying to connect Channeble with the Datahub.

I've added the API and I'm following the steps to add the Project ID.

In Channable, I've selected the project, opened the project setup and copied the Project ID.
![image](https://github.com/Gladior-B-V/data-hub-app/assets/26337936/b8e2ac54-5a79-473f-9a81-c3c1c1b69d04)

If I then go to the Datahub app and fill in the Project ID, it's not accepting it.
![image](https://github.com/Gladior-B-V/data-hub-app/assets/26337936/ce427808-b74e-402c-bedd-8016aaaa3a0a)

I can see the following errors in the console.
![image](https://github.com/Gladior-B-V/data-hub-app/assets/26337936/12aab37c-eda7-464e-bd4e-a4a12174aa7d)

Any idea what is going on or how I can make the connection?

Many thanks in advance!

Kind Regards,
Oscar

**Comment by rkooiker** [comment]
Hi, 

We have fixed this issue.

Kind regards,
Rob Kooiker
