### ISSUE TITLE
Getting Error: "Cannot Connect to Data Source" & "No options were provided for "Facebook Ads Account"

### ISSUE THREAD

**Issue by jerry-from-mesmero** [Gladior-B-V/data-hub-app#43]
All of my connectors for Facebook have stopped working.  
I am using a Gmail business email account to access Facebook.
When I try to 'Reconnect" or Add a New Data Source, the drop down is blank and I get these errors:

"Cannot Connect to Data Source" & "No options were provided for "Facebook Ads Account". Check if you have the correct account/rights."

Below are screen grabs of th 
![Screenshot 2024-07-24 at 12 11 43 PM](https://github.com/user-attachments/assets/59470c67-2325-4a86-ba10-df793b85cf94)

![Screenshot 2024-07-24 at 12 11 57 PM](https://github.com/user-attachments/assets/889e5317-dc77-40bc-bd51-f87e9d66657c)

**Comment by rkooiker** [comment]
Hi,

Could you try to reconnect the credential?

**Comment by jerry-from-mesmero** [comment]
Hmmm, I'm still unable to connect. 
![Screenshot 2024-07-30 at 2 11 19 PM](https://github.com/user-attachments/assets/80b25607-b46b-4222-bdec-482e73cf2b38)
![Screenshot 2024-07-30 at 2 12 22 PM](https://github.com/user-attachments/assets/fa5c5045-d86f-4f78-88ed-c593db379465)

**Comment by rkooiker** [comment]
Something must have gone wrong while reconecting the credential. Our logs show that the last attempt was on the 15th of May. Since the facebook credential needs to be reconnected every 60 days it will have expired already. Could you try to reconnect again? You should be redirected to facebook, and asked to login.
