### ISSUE TITLE
Facebook Ads connector issue

### ISSUE THREAD

**Issue by giolido** [Gladior-B-V/data-hub-app#45]
Hi there, 

I get the following error:

![2024-08-14_09-22-25](https://github.com/user-attachments/assets/4dbb5985-4f3b-419e-af8a-d4ca5cc8c503)

It was working normally until yesterday. 

Is there a fix on the way?

Thanks  alot

**Comment by giolido** [comment]
i tried reconnecting but nothing...  :(

**Comment by rkooiker** [comment]
hi @giolido, 

This issue has been resolved

**Comment by giolido** [comment]
Great! Thanks a lot!
