### ISSUE TITLE
Datahub is not showing any options or links responsive

### ISSUE THREAD

**Issue by seotrackerman** [Gladior-B-V/data-hub-app#47]
Hi there, I recently changed my login password for FB and now the connector isn' working. When I go into the connect i get a notification to fix creditentials, however when I click on Fix issues, nothing happens or pops up. Likewise when i try to reconnect from looker, the workspace appears empty, and even nothing happens when i click create. 

I checked if there were any pop-ups blocked but cannot see anything.

Hoping you can help.

**Comment by rkooiker** [comment]
Hi @seotrackerman,

Everything should work as expected again now. After you reconnect the facebook credential the data should also be available again.
