### ISSUE TITLE
Data Hub isnt loading properly

### ISSUE THREAD

**Issue by tajs-everyday** [Gladior-B-V/data-hub-app#48]
When I login I don't see the list of all data sources made.
In Console it keeps returning the same 500 Error

cwr.js:2 
       GET https://data-provider-api.dh.gladior.com/data-providers/usage?dataSourceId=&outputMode=datahub_dataproviderdata 500 (Internal Server Error)

**Comment by rkooiker** [comment]
Hi @tajs-everyday,

This has been fixed now.
