### ISSUE TITLE
Facebook Insights page fans data is missing

### ISSUE THREAD

**Issue by ESGITR** [Gladior-B-V/data-hub-app#5]
I'm unable to connect to the pagefan data. 

![image](https://user-images.githubusercontent.com/99658324/207036216-df4cdf16-306c-47ba-9524-0c5473707ab2.png)

**Comment by zoedufrenne** [comment]
@ESGITR We've made an update to the connector. Pagefans data is now available again. Could you refresh the dashboard, and check if the data is complete?
