### ISSUE TITLE
Error on Google Business Profile connection

### ISSUE THREAD

**Issue by Avenirdata** [Gladior-B-V/data-hub-app#7]
Good day,

I have this error :

Choose a Group
Avenir Data
Choose a Location
Location
Unknown Error - There was an error communicating with the data provider.
O No options were provided for "Location". Check if you have the correct account/rights.

Thanks for your work, regards,

Stéphane Olaïzola

**Comment by zoedufrenne** [comment]
Hi @Avenirdata 
As I read the error message it says:  "No options were provided for "Location". Check if you have the correct account/rights." Do you have locations attached to the group? Avenir Data or is there maybe an other group where the locations are attached?
