### ISSUE TITLE
I can't enter in my workspace

### ISSUE THREAD

**Issue by CTFCR** [Gladior-B-V/data-hub-app#9]
Hello, 

I can't enter in my workspace. When I sign in, I have this page : 
![Capture](https://user-images.githubusercontent.com/123931354/215504950-0b876b0b-c33d-4e9e-a445-3ce069bef848.PNG)

And when I click on my name, it reloads the same page. Before the issue, it was working perfecly.

Can you help me to resolve the issue ?

Thank you

**Comment by zoedufrenne** [comment]
@CTFCR Thanks for reporting. I'd like to take a look.
Can you send me your user ID? datahubapp.gladior.com -> Edit Profile -> gray ID at the bottom of the page

**Comment by zoedufrenne** [comment]
Hi @CTFCR, Thanks for reporting. 
We are currently working on a workaround for a few people this is an issue. I'll keep you updated when we have a solution.

**Comment by zoedufrenne** [comment]
Hi @CTFCR We've made an adjustment to the data hub, this adjustment should resolve your issue. Can you try again to enter your workspace?

**Comment by CTFCR** [comment]
Hello,

It's working, thank you !

Have a nice day,
Céline

De : zoedufrenne ***@***.***>
Envoyé : dinsdag 31 januari 2023 14:27
À : Gladior-B-V/data-hub-app ***@***.***>
Cc : Timmermans, Celine ***@***.***>; Mention ***@***.***>
Objet : Re: [Gladior-B-V/data-hub-app] I can't enter in my workspace (Issue #9)


Hi @CTFCR<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCTFCR&data=05%7C01%7Cceline.timmermans%40fcrmedia.be%7C5c81e4b2d361418b84dc08db038ee31f%7Cc93c6954220a4a4788c41d8ec0ae031a%7C0%7C0%7C638107684449783857%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AD6EkbX1JBa4EGDLerzCG3%2B2abAbcb%2Btf2Xvq6nczok%3D&reserved=0> We've made an adjustment to the data hub, this adjustment should resolve your issue. Can you try again to enter your workspace?

-
